import { Menu } from '@headlessui/react';
import Cookies from 'js-cookie';
import { signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect, useState } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { cartType, Store } from '../utils/Store';

const Layout: React.FC<{ children: any; title?: string }> = ({
  children,
  title,
}) => {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  const { status, data: session } = useSession();
  useEffect(() => {
    setCartItemsCount(
      cart.cartItems.reduce((a: any, c: { quantity: any }) => a + c.quantity, 0)
    );
  }, [cart.cartItems]);

  const logoutHandler = () => {
    Cookies.remove('cart');
    dispatch({ type: 'CART_RESET_ACTION' });
    signOut({ callbackUrl: '/login' });
  };
  return (
    <React.Fragment>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="bottom-right" limit={1} />
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 justify-between shadow-md items-center px-4">
            <Link href="/" className="text-lg font-bold text-black">
              Amazona
            </Link>
            <div>
              <Link href="/cart" className="p-2">
                Cart
                {cartItemsCount > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 text-xs font-bold text-white">
                    {cart.cartItems.reduce(
                      (a: any, c: { quantity: any }) => a + c.quantity,
                      0
                    )}
                  </span>
                )}
              </Link>
              <p className="inline">
                {status === 'loading' ? (
                  'loading'
                ) : session?.user ? (
                  <Menu as="div" className="relative inline-block">
                    <Menu.Button className="text-blue-600">
                      {session.user.name}
                    </Menu.Button>
                    <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white shadow-lg">
                      <Menu.Item>
                        <Link href="/profile" className="dropdown-link">
                          Profile
                        </Link>
                      </Menu.Item>
                      <Menu.Item>
                        <Link href="/order-history" className="dropdown-link">
                          Order History
                        </Link>
                      </Menu.Item>
                      {session.user.isAdmin && (
                        <Menu.Item>
                          <Link
                            href="/admin/dashboard"
                            className="dropdown-link"
                          >
                            Dashboard
                          </Link>
                        </Menu.Item>
                      )}
                      <Menu.Item>
                        <Link
                          href=""
                          className="dropdown-link"
                          onClick={logoutHandler}
                        >
                          Logout
                        </Link>
                      </Menu.Item>
                    </Menu.Items>
                  </Menu>
                ) : (
                  <Link href="/login" className="p-2">
                    Login
                  </Link>
                )}
              </p>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          <p>Copyright © 2022 Amazona</p>
        </footer>
      </div>
    </React.Fragment>
  );
};

export default Layout;
